### PR TITLE
Don't sanitize HTML since workshops are manually reviewed

### PR DESCRIPTION
**Pull request by khrj**
Don't sanitize HTML since workshops are manually reviewed
cc @sampoder
fixes https://workshops.hackclub.com/web_chat/

### CODE REVIEW

**Comment by sampoder** [comment]
personal thoughts I would keep.sanitization and just edit the schema to include videos

**Comment by khrj** [comment]
Hmmm why though? I mean aren't workshops throughly checked anyway?

**Comment by lachlanjc** [comment]
Hey! I'd like to keep the sanitization, since the package itself is designed to be a general-purpose Markdown parser. What specific issue is it causing on that workshop this would fix?

**Comment by khrj** [comment]
In my workshop, the <video> element isn’t rendered, it was sanitised and replaced by it’s alt text
See: https://workshops.hackclub.com/web_chat/
Under #### Repl.it basics

**Comment by lachlanjc** [comment]
Got it. Yeah, if we can pass it options & allow videos, that sounds amazing

**Comment by sampoder** [comment]
I feel like this can be closed, thoughts @KhushrajRathod?

**Comment by khrj** [comment]
Yeah ig, although it's still broken, but for the time being it's okay because of the alt text

**Pull request closed without merging**
